# Copyright (c) 2022 STMicroelectronics
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: openamp
      url-base: https://github.com/OpenAMP
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: openamp

  self:
    path: openamp-system-reference

  projects:
    - name: zephyr
      remote: zephyr
      revision: v3.6.0
      import: true

    # as we use the same names as in the zephyr manifest,
    # our definitions eclipse their's
    - name: libmetal
      revision: main

    - name: open-amp
      revision: main

    # however, our version does not have the zephyr module glue
    # so bring in our custom version that integrates both libraries
    # as a single zephyr module
    - name: openamp-zephyr-modules
      revision: main
