# Copyright (c) 2022 STMicroelectronics
# SPDX-License-Identifier: Apache-2.0

manifest:
  remotes:
    - name: openamp
      url-base: https://github.com/OpenAMP
    - name: zephyr
      url-base: https://github.com/zephyrproject-rtos
  defaults:
    remote: openamp

  self:
    path: openamp-system-reference

  projects:
    - name: zephyr
      remote: zephyr
      revision: v3.5.0
      import: true
