collect(PROJECT_LIB_DEPS c)
collect(PROJECT_LIB_DEPS xil)
collect(PROJECT_LIB_DEPS xiltimer)
collect(PROJECT_LIB_DEPS xilstandalone)
collect(PROJECT_LIB_DEPS metal)
collect(PROJECT_LIB_DEPS metal_xlnx_extension)

find_library (_xilpm_lib_path "xilpm")
if (_xilpm_lib_path)
  collect(PROJECT_LIB_DEPS "xilpm")
else()
  collect(PROJECT_LIB_DEPS "xilpm_ng")
endif(_xilpm_lib_path)
